/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ArbolVisual;

import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JFrame;
import voronoi.Punto;
import voronoi.tree.VoronoiTree;

/**
 *
 * @author JosePertierra
 */
public class visualizarArbol extends javax.swing.JFrame {

    /**
     * Creates new form visualizarArbol
     */
    public visualizarArbol(VoronoiTree arbolito) {
        
        System.out.println("Visualizacion de árbol iniciada");
        initComponents();
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        this.setTitle("Árbol de Parábolas");
//        VoronoiTree arbolito = new VoronoiTree();
//        voronoi.Punto nuevoPunto = new voronoi.Punto(3,4);
//        arbolito.insert(nuevoPunto);
//        System.out.println(arbolito.toString());
//        nuevoPunto = new voronoi.Punto(2,1);
//        arbolito.insert(nuevoPunto);
//        System.out.println(arbolito.toString());
//        nuevoPunto = new voronoi.Punto(8,0);
//        arbolito.insert(nuevoPunto);
//        System.out.println(arbolito.toString());
//        nuevoPunto = new voronoi.Punto(7,-1);
//        arbolito.insert(nuevoPunto);
//        System.out.println(arbolito.toString());
        visualArbol1.setArbol(arbolito);
        visualArbol1.setVentana(this);
    }
    
    public void escribirPuntos(ArrayList<String> lista){
        ArrayList<String> puntos = lista;
        String[] strAux = (String[]) Arrays.copyOf(lista.toArray(),lista.size(),String[].class);
        System.out.println("Strings: "+Arrays.toString(strAux));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = strAux;
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        visualArbol1 = new ArbolVisual.visualArbol();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        visualArbol1.setBackground(new java.awt.Color(255, 255, 255));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout visualArbol1Layout = new javax.swing.GroupLayout(visualArbol1);
        visualArbol1.setLayout(visualArbol1Layout);
        visualArbol1Layout.setHorizontalGroup(
            visualArbol1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(visualArbol1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 654, Short.MAX_VALUE))
        );
        visualArbol1Layout.setVerticalGroup(
            visualArbol1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(visualArbol1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(visualArbol1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public void ejecutar(VoronoiTree arbolito) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private ArbolVisual.visualArbol visualArbol1;
    // End of variables declaration//GEN-END:variables
}
