/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazfortune;

import java.awt.Cursor;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;
import voronoi.*;
import voronoi.tree.VoronoiTree;

/**
 *
 * @author JosePertierra
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    
    int estado = 0;
    int directriz = 0;
    FortuneQueue colaEventos;
    Iterator<Event> iter;
    
    /*
    0 .- Nada
    1 .- Crear nuevos puntos
    2 .- Mover puntos
    */
    
    public Ventana() {
        initComponents();
        this.setTitle("Diagrama de Voronoi");
        lienzo1.addMouseMotionListener(new MouseMotionListener() {
            PuntoDibujo aux;
            @Override
            public void mouseDragged(MouseEvent e) {
                if (aux!= null){
                    System.out.println("Draggeado");
                    aux.setX(e.getX());
                    aux.setY(e.getY());
                    lienzo1.repaint();
                }
                setCoordenadas(e.getX(),lienzo1.getHeight()-e.getY());
            }

            @Override
            public void mouseMoved(MouseEvent e) {
                if (estado == 2){
                    aux = lienzo1.buscarColision(e.getX(),e.getY());
                    if (aux != null){
                        lienzo1.setCursor(new Cursor(Cursor.HAND_CURSOR));
                    }else{
                        lienzo1.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                    }
                    
                }  
                setCoordenadas(e.getX(),lienzo1.getHeight()-e.getY());
                
            }
        });
        
        lienzo1.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                //
            }

            @Override
            public void mousePressed(MouseEvent e) {
                if (estado == 1){
                    lienzo1.addPoint(e.getX(),e.getY());
                    lienzo1.repaint();
                    System.out.println("Pintado el punto: "+e.getX()+" - "+e.getY());
                }
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void mouseExited(MouseEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }
    
    public void setCoordenadas(int x,int y){
        jLabel1.setText("Coordenadas: "+x+" , "+y);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        lienzo1 = new interfazfortune.lienzo();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Nuevo Punto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Mover Puntos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Procesar Voronoi");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("Árbol");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Siguiente Event->");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel1.setText("Coordenadas: ");
        jLabel1.setToolTipText("Coordenadas");

        javax.swing.GroupLayout lienzo1Layout = new javax.swing.GroupLayout(lienzo1);
        lienzo1.setLayout(lienzo1Layout);
        lienzo1Layout.setHorizontalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lienzo1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
        lienzo1Layout.setVerticalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lienzo1Layout.createSequentialGroup()
                .addGap(0, 538, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jButton4.setText("Ejecutar Fortune");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Abrir");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Guardar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Edición");

        jMenuItem3.setText("Eliminar todo");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(2, 2, 2)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addGap(0, 214, Short.MAX_VALUE))
            .addComponent(lienzo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3)
                        .addComponent(jButton5)
                        .addComponent(jButton6))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)
                        .addComponent(jButton4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lienzo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.estado = 1;
        lienzo1.setCursor(new Cursor(Cursor.CROSSHAIR_CURSOR));
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.estado = 2;
        lienzo1.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        colaEventos = new FortuneQueue();
        for (PuntoDibujo p :lienzo1.getPuntos()){
            colaEventos.add(new SiteEvent(new Punto(p.getX(),lienzo1.getSize().height-p.getY())));
        }
        this.iter = colaEventos.getQueue().iterator();
        lienzo1.procesarArbol();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void siguienteEvent(){
        System.out.println("Buscando evento siguiente");
        int directriz = (int) this.getSize().getHeight();
        if (this.iter.hasNext()){
            Event eventoAux = iter.next();
            directriz = (int) eventoAux.getEvent().getY();
        }else{
            System.out.println("No quedan mas events");
            directriz = 0;
        }
        Iterator<Event> aux = colaEventos.getQueue().iterator();
        ArrayList<Parabola> listaPar = new ArrayList<Parabola>();
        while (aux.hasNext()){
            Punto e = aux.next().getEvent();
            listaPar.add(new Parabola((int) e.getX(),(int) e.getY(),directriz));
            System.out.println("Evento: "+e.getX()+","+e.getY());
        }
        lienzo1.setParabolas(listaPar);
        lienzo1.repaint();
        lienzo1.recorrerFrenteDeParabolas();
    }
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        lienzo1.mostrarArbol();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.siguienteEvent();
    }//GEN-LAST:event_jButton6ActionPerformed
    
    private void ejecucionDeVoronoi(){
        // TODO add your handling code here:
        ArrayList<PuntoDibujo> arrPuntos = lienzo1.getPuntos();
        Set<Punto> listapuntos = new HashSet <Punto>();
        for (PuntoDibujo p : arrPuntos){
            Punto paux = new Punto(p.getX(),p.getY());
            System.out.println("Añadido punto: "+paux);
            listapuntos.add(paux);
        }
        
        Voronoi v = new Voronoi();
        DCEL salida = new DCEL();
        
        System.out.println("Obtenida la salida del Voronoi");
        salida = v.Voronoi(listapuntos);
        System.out.println(salida.toString());
        lienzo1.eliminarVerticesAristas();
        for (Vertice vert : salida.getListaVertices()){
            PuntoDibujo pAux = new PuntoDibujo((int)vert.getX(),(int)vert.getY());
            lienzo1.addVertice(pAux);
        }
        ArrayList<Arista> arr = salida.getListaAristas();
        RectaDibujo r;
        for (Arista a : arr){
            PuntoDibujo ini;
            PuntoDibujo fin;
            if (a.getpFin()!= null){
                fin = new PuntoDibujo((int) a.getpFin().getX(),(int) a.getpFin().getY());
            }else{
                fin = null;
            }
            if (a.getpNacimiento()!=null){
                ini = new PuntoDibujo((int) a.getpNacimiento().getX(),(int) a.getpNacimiento().getY());
            }else{
                ini = null;
            }
            r = new RectaDibujo(ini,fin);
            lienzo1.addArista(r);
        }
        lienzo1.repaint();
    }
    
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        eliminarTodo();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.ejecucionDeVoronoi();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }
    
    private void eliminarTodo(){
        lienzo1.eliminarTodo();
        lienzo1.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private interfazfortune.lienzo lienzo1;
    // End of variables declaration//GEN-END:variables
}
